# Generated by Django 3.2.3 on 2022-03-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('online_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assignments', to='resources.onlineclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
