# Generated by Django 3.2.3 on 2022-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_teacher_students_in_class'),
        ('resources', '0003_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='students_in_class',
            field=models.ManyToManyField(related_name='online_class', to='students.Student'),
        ),
    ]
