# Generated by Django 3.2.3 on 2022-03-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_teacher_students_in_class'),
        ('resources', '0004_onlineclass_students_in_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='students.student'),
        ),
    ]
