# Generated by Django 3.2.3 on 2022-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20220317_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
